name : build the webstie and upload zip file
on: push 
jobs: 
    first-job:
        runs-on: ubuntu-latest
        container: node:20
        steps:
         - run : node --version
         - run: npm --version 
         - uses: actions/checkout@v4
         - run : npm i
         - run : npm run build
         - run : zip -r test.zip dist/
         
         - uses: actions/upload-artifact@v3
           with:
                name: webstie-build
                path : test.zip 
