on: push 
jobs: 
    first-job:
        runs-on: ubuntu-latest
        container: node:20
        steps:
         - run : node --version
         - run: npm --verion 
         - uses: actions/checkout@v4
         - run : npm i
         - run : npm build