name : build the webstie and upload zip file
on: workflow_call
jobs: 
    first-job:
        runs-on: ubuntu-latest
        container: node:20
        steps:
         - run : node --version
         - run: npm --version 
         - uses: actions/checkout@v4
         - run : npm i
         - run : npm run build

         
         - uses: actions/upload-artifact@v3
           with:
                name: webstie-build
                path : dist/
